language: php

php:
  - hhvm
  - 5.6
  - 5.5
  - 5.4

install:
  - composer install --dev --prefer-source

befor_script:
  - composer require satooshi/php-coveralls
  - mkdir -p build/logs

script:
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
